description: "Options for UNet"

data:
    data_dir:  '../data/float32' # relative path to data directory
    data_type: 'TIME_NOISE'      # 'TIME', 'TIME_NOISE', 'RATE', 'RATE_DURATION'
    Ntrain:    1024
    Nvalidate: 2048
    Ntest:     2048
    train_shuffle_buffer_size: 1000
    train_batch_size: 256
    eval_batch_size:  256
    random_seed: 123

net:
    conv_internal_channels: 32
    conv_channel_mult:
        - 1
        - 2
        - 4

optimizer:
    learning_rate: 0.001
    beta1: 0.9
    beta2: 0.999
    epsilon: 1.0e-8

training:
    epochs: 100

runconfig:
    mode: 'TRAIN'
    load_dir: #'runs/unet_dir'
    save_dir:  'runs/unet_dir'
    log_epochs: 1
    save_checkpoints_epochs: 50
    debug: True
    show_plots: False
