description: "Options for DNN-based inverse maps"

data:
    data_dir:  '../data/float32' # relative path to data directory
    data_type: 'TIME_NOISE'      # 'TIME', 'TIME_NOISE', 'RATE', 'RATE_DURATION'
    Ntrain:    1024
    Nvalidate: 2048
    Ntest:     2048
    train_shuffle_buffer_size: 1000
    train_batch_size: 256
    eval_batch_size:  256
    random_seed: 123
    autoencoder_load_dir: #'runs/ae_dir'
    autoencoder_latent_dim: 16  # e.g., 2, 4, 16, 64, 125

net:
    type: 'MLPResNet'  # 'MLPNet', 'MLPResNet', 'ConvNet', 'TransformerNet' (prototype)
    activation_fn: 'gelu'  # 'relu', 'silu' or 'swish', 'gelu'
    dropout: #0.2

    conv_layer_sizes:
        - 8
        - 16
        - 32

    dense_layer_sizes:
        - 128
        - 128
        - 128
        - 128
        - 128
        - 128
        - 128
        - 128

    residual_blocks_sizes:
        -
            - 32
            - 32
            - 128
            - 32
        -
            - 32
            - 32
            - 128
            - 32
        -
            - 32
            - 32
            - 128
            - 32
        -
            - 32
            - 32
            - 128
            - 32

    transformer_embedding_size: 32
    transformer_n_heads: 4
    transformer_feedforward_size: 256

optimizer:
    type: 'AdamW'  # 'Adam', 'AdamW'
    learning_rate: 1.0e-2
    beta1: 0.9
    beta2: 0.999
    epsilon: 1.0e-8
    weight_decay: 0.01  # used in AdamW
    learning_rate_scheduler:
        init_learning_rate: 1.0e-3
        linear_epochs:   50  # num epochs to get from `init_learning_rate` to `learning_rate`
        constant_epochs: 50  # num epochs to stay at `learning_rate`
        final_learning_rate: 1.0e-4

training:
    epochs: 400

runconfig:
    mode: 'TRAIN'
    load_dir: #'runs/dnn_dir'
    save_dir:  'runs/dnn_dir'
    log_epochs: 1
    save_checkpoints_epochs: 50
    debug: True
    show_plots: False
