description: "Options for DNN-based inverse maps"

data:
    data_dir:  '../data/float32' # relative path to data directory
    data_type: 'TIME_NOISE'      # 'TIME', 'TIME_NOISE', 'RATE', 'RATE_DURATION'
    Ntrain:    1024
    Nvalidate: 2048
    Ntest:     2048
    train_shuffle_buffer_size: 1000
    train_batch_size: 256
    eval_batch_size:  256
    random_seed: 123

net:
    type: 'convNet'  # 'denseNet', 'convNet', 'transformerNet' (prototype)
    conv_layer_sizes:
        - 8
        - 16
        - 32
    dense_layer_sizes:
        - 32
        - 32
        - 32
        - 32
    activation_fn: 'gelu'  # 'relu', 'silu' or 'swish', 'gelu'
    transformer_embedding_size: 32
    transformer_n_heads: 4
    transformer_feedforward_size: 256
    dropout: #0.2

optimizer:
    learning_rate: 0.002
    beta1: 0.9
    beta2: 0.999
    epsilon: 1.0e-8

training:
    epochs: 200

runconfig:
    mode: 'TRAIN'
    load_dir: #'runs/dnn_dir'
    save_dir:  'runs/dnn_dir'
    log_epochs: 1
    save_checkpoints_epochs: 50
    debug: True
    show_plots: False
